CREATE TABLE IF NOT EXISTS baseTaskLog (
    id INT PRIMARY KEY AUTO_INCREMENT,
    taskAction VARCHAR(255) NOT NULL,
    taskName VARCHAR(255) NOT NULL,
    createdDateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS test (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    createdDateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS schedules (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NULL,
    createdDate DATE NOT NULL DEFAULT CURRENT_DATE,
    startDate TIMESTAMP NOT NULL,
    endDate TIMESTAMP NOT NULL,
    startTime TIME NULL,
    endTime TIME NULL,
    priorityName VARCHAR(50) NULL  
);
